### ISSUE TITLE
refactor daemon to be containerd + plugins

### ISSUE THREAD

**Issue by dweomer** [rancher/k3c#24]
The CRI plugin attaches it's API to the `containerd` socket. We should do more of this!
- `k3c daemon` should be a `containerd` CLI work-alike
- containerd plugin to expose k3c API on the gRPC socket
- containerd plugin to expose buildkit API on the gRPC socket

**Comment by alexellis** [comment]
How will that change the UX?

**Comment by dweomer** [comment]
For my initial cut at this `k3c daemon` has almost the exact same UX as `containerd`
