### ISSUE TITLE
flag provided but not defined: -group

### ISSUE THREAD

**Issue by bennidhamma** [rancher/k3c#58]
Downloaded the latest release (v0.2.0-rc.13, k3c-linux-amd64) and also downloaded and built source. But when I try to run as I believe the instructions intend, I get this error:

`$ sudo ./bin/k3c daemon --group=$(id -g) --bootstrap-image=docker.io/rancher/k3c:dev
Incorrect Usage. flag provided but not defined: -group
`

Thank you, very excited about getting this working!

**Comment by dweomer** [comment]
@bennidhamma that have has been temporarily removed. I will add it back and cut another RC.

**Comment by bennidhamma** [comment]
Thanks! I think I'm in a bit over my head. I'm playing with skaffolds and k3d with a local registry for now, but I'm really excited about this project and will follow closely. Just seems a bit advanced for where I currently am with k8s!

But, I love the concept and am staying tuned!
