### ISSUE TITLE
Wrong gopath

### ISSUE THREAD

**Issue by alexellis** [rancher/k3c#7]
This project can't be built in the GOPATH shown on GitHub:

```
$GOPATH/src/github.com/ibuildthecloud/k3c
```

It complains and needs to be cloned at:

```
$GOPATH/src/github.com/rancher/k3c
```

I suspect that the use of modules may be why this works for you, but documenting it, or documenting build instructions would be useful.

**Comment by ibuildthecloud** [comment]
The intended home for this project is `github.com/rancher/k3c`.  I'll move it over in the coming week or so as I get things all sorted out.
